name: klime
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_spinkit: ^4.0.0
  font_awesome_flutter: ^8.11.0
  flutter_circular_chart: ^0.1.0
  geolocator: ^6.0.0
  dio: ^3.0.10
  pull_to_refresh: 1.6.3
  connectivity: 2.0.2
  fluttertoast: ^7.1.8
  fl_chart: 0.12.3
  get_storage: 1.4.0
  dio_http_cache: ^0.2.11
  url_launcher: 5.7.10
  date_util: ^0.1.4
#  location: 3.2.0
#  permission_handler: 5.1.0
#  permission_handler: 6.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.otf
        - asset: fonts/Poppins-Bold.otf
          weight: 700
        - asset: fonts/Poppins-Medium.otf
          weight: 200
        - asset: fonts/Poppins-Light.otf
          weight: 100
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
